### ISSUE TITLE
Search works only for repos

### ISSUE THREAD

**Issue by arunthampi** [asknestor-apps/github#1]
first found by @cheeaun

**Comment by cheeaun** [comment]
Screenshot for reference :+1: 

<img width="416" alt="screen shot 2016-03-23 at 12 34 52 pm" src="https://cloud.githubusercontent.com/assets/2296/13975744/ac67fa98-f0f3-11e5-9f57-93a3a6de381b.png">

**Comment by cheeaun** [comment]
:+1:
